// Public entrypoint for the shared lexicons package.
//
// Re-exports the code generated by `@atcute/lex-cli` (run `pnpm generate`).
// Each lexicon is exposed as a namespace, e.g. `PubAtmoNotifySend`, carrying:
//   - `mainSchema`  — the XRPC metadata you pass to `XRPCRouter.add*`
//   - `$input` / `$output` / `$params` — inferred request/response types
//   - view types for `ref`'d defs (e.g. `GrantView`)
//
// Importing these modules also augments `@atcute/lexicons/ambient`'s
// `XRPCQueries` / `XRPCProcedures` registries with our NSIDs.
export * from './lexicons/index.js';

// Hand-written: the first-party management contract shared by the relay's
// service-binding entrypoint and the web app (see ./rpc.ts).
export * from './rpc.js';
