// Hand-written (NOT generated by lex-cli, which only writes ./lexicons/).
//
// The relay's first-party management API. These 11 methods are deliberately NOT
// public XRPC: the relay exposes them ONLY over a Cloudflare service binding to
// the web app's server (see apps/relay/src/rpc/entrypoint.ts). This interface is
// the single contract both ends share — the relay's `RelayRpc` entrypoint
// `implements NotifsRpc`, and the web app types its `platform.env.RELAY` binding
// as `NotifsRpc`, so every call is type-checked end-to-end off the same source.
//
// Shapes reuse the lex-cli-generated `$input`/`$output` types, so the lexicon
// JSON stays the source of truth for request/response bodies even though these
// methods are no longer served as XRPC. The leading `did` argument is the
// authenticated user the caller (the trusted web server) vouches for.
import type { Did } from '@atcute/lexicons';

import type {
  PubAtmoNotifyDenyPending,
  PubAtmoNotifyGetSettings,
  PubAtmoNotifyGrant,
  PubAtmoNotifyLinkChannel,
  PubAtmoNotifyListGrants,
  PubAtmoNotifyListPending,
  PubAtmoNotifyMuteGrant,
  PubAtmoNotifyRevoke,
  PubAtmoNotifyUpdateSettings,
} from './lexicons/index.js';

/** A browser PushSubscription, flattened (binding-only; no public lexicon). */
export interface PushSubscriptionInput {
  endpoint: string;
  p256dh: string;
  auth: string;
  /** Device label: a user-chosen name if `named`, else the auto User-Agent
   *  descriptor; preserved across re-subscribes. */
  label?: string;
  /** True when `label` is a user-chosen name (shown to apps as-is). */
  named?: boolean;
}

/**
 * One of a user's delivery targets — a push device, a Telegram chat, an email,
 * a Bluesky DM, or a webhook (binding-only). Discriminated by `channel`. `id` is
 * the stable token a route uses to target this instance; `label` is the
 * user-editable name.
 */
export type TargetView =
  | { id: string; channel: 'push'; label: string; endpoint: string; createdAt: string }
  | { id: string; channel: 'telegram'; label: string; createdAt: string }
  | {
      id: string;
      channel: 'email';
      label: string;
      address: string;
      /** false while a verification code is outstanding. */
      verified: boolean;
      createdAt: string;
    }
  | { id: string; channel: 'dm'; label: string; createdAt: string }
  | { id: string; channel: 'webhook'; label: string; url: string; createdAt: string };

/** One person behind a notification (for the avatar stack). */
export interface NotificationActor {
  /** The actor's DID (stable identifier). */
  did: string;
  /** The actor's handle, for display — sender-supplied or resolved. */
  handle?: string;
  /** Resolved avatar image URL — sender-supplied `avatarImage` or fetched from the DID. */
  avatar?: string;
  /** Optional link for the actor (e.g. their profile), for clickable avatars. */
  url?: string;
}

/** A notification as shown in the inbox (binding-only; no public lexicon). */
export interface NotificationView {
  id: string;
  sender: Did;
  /** Display name for the sending app (the icon's alt + its fallback initial). */
  senderTitle: string;
  /** Best-effort app icon: app-supplied icon → catalog → the sender's Bluesky avatar. */
  iconUrl?: string;
  category?: string;
  title: string;
  body: string;
  uri?: string;
  actors: NotificationActor[];
  createdAt: string;
  read: boolean;
}

export interface ListNotificationsResult {
  notifications: NotificationView[];
  /** `created_at` cursor for the next (older) page; absent when there are no more. */
  cursor?: string;
  unread: number;
}

export interface MarkReadInput {
  ids?: string[];
  all?: boolean;
}

/** The alert channels a route can fire. Everything is in the inbox regardless. */
export const CHANNELS = ['push', 'telegram', 'email', 'dm', 'webhook'] as const;
export type Channel = (typeof CHANNELS)[number];

// A route is a `+`-joined set of TOKENS in canonical CHANNELS order ('off' = none).
// A token is either a bare channel ('push' = all instances of that channel) or a
// channel with a specific instance id ('push:<id>' = just that device/chat), so a
// user can route to one of several push devices / telegram chats. Examples:
// 'push', 'push+email', 'push:a1b2c3', 'push:a1b2c3+telegram', 'off'. App-wide and
// per-category routes add the inherit sentinels 'default' / 'app'. Stored as a
// string; legacy values ('push'/'telegram'/'push+telegram'/'off') are valid sets.
/** A concrete route: a `+`-joined token set, or 'off'. */
export type AlertRoute = string;
/** App-wide route: a concrete route, or 'default' (inherit the account default). */
export type AppRoute = string;
/** Per-category route: a concrete route, or 'app' (inherit the app-wide route). */
export type CategoryRoute = string;

/** A parsed route token: a channel, optionally narrowed to one instance id. */
export interface RouteToken {
  channel: Channel;
  /** A specific delivery-instance id (see RouteInstance); absent = all instances. */
  instance?: string;
}

/** Instance-id format: nanoid's url-safe alphabet (A–Z a–z 0–9 _ -); see lib/ids newTargetId. */
const INSTANCE_ID_RE = /^[A-Za-z0-9_-]+$/;

/** True for routes that carry no channel tokens: the inherit sentinels, plus
 *  'off' (drop entirely) and 'inbox' (inbox only, no alerts), and ''. */
function isSentinel(route: string): boolean {
  return (
    route === 'off' ||
    route === 'inbox' ||
    route === 'default' ||
    route === 'app' ||
    route === ''
  );
}

/** Parse a route string into its tokens (sentinels/'' → []). Unknown channels skipped. */
export function parseRoute(route: string): RouteToken[] {
  if (isSentinel(route)) return [];
  const tokens: RouteToken[] = [];
  for (const part of route.split('+')) {
    const idx = part.indexOf(':');
    const channel = (idx === -1 ? part : part.slice(0, idx)) as Channel;
    if (!(CHANNELS as readonly string[]).includes(channel)) continue;
    const instance = idx === -1 ? undefined : part.slice(idx + 1);
    tokens.push(instance ? { channel, instance } : { channel });
  }
  return tokens;
}

/** Encode tokens as a canonical route string ('off' when empty). A bare channel
 *  token subsumes any instance tokens for the same channel. */
export function formatRoute(tokens: readonly RouteToken[]): string {
  const parts: string[] = [];
  for (const c of CHANNELS) {
    const forChannel = tokens.filter((t) => t.channel === c);
    if (forChannel.length === 0) continue;
    if (forChannel.some((t) => t.instance === undefined)) {
      parts.push(c);
      continue;
    }
    const seen = new Set<string>();
    for (const t of forChannel) {
      if (t.instance !== undefined && !seen.has(t.instance)) {
        seen.add(t.instance);
        parts.push(`${c}:${t.instance}`);
      }
    }
  }
  return parts.length > 0 ? parts.join('+') : 'off';
}

/** The distinct channels a route fires ('off'/'default'/'app'/'' → []). */
export function routeChannels(route: string): Channel[] {
  const present = new Set<Channel>();
  for (const t of parseRoute(route)) present.add(t.channel);
  return CHANNELS.filter((c) => present.has(c));
}

/** Encode whole channels as a canonical route string ('off' when empty) — each
 *  fires all of that channel's instances. */
export function channelsRoute(channels: readonly Channel[]): string {
  return formatRoute(CHANNELS.filter((c) => channels.includes(c)).map((channel) => ({ channel })));
}

/** Per-channel instance selection parsed from a route. An absent channel is not
 *  fired; `all` fires every instance; otherwise only the listed instance ids. */
export type RouteSelection = Partial<Record<Channel, { all: boolean; ids: string[] }>>;

/** Resolve a route to its per-channel instance selection (used by delivery). */
export function routeSelection(route: string): RouteSelection {
  const sel: RouteSelection = {};
  for (const tok of parseRoute(route)) {
    const cur = sel[tok.channel] ?? { all: false, ids: [] };
    if (tok.instance === undefined) cur.all = true;
    else cur.ids.push(tok.instance);
    sel[tok.channel] = cur;
  }
  return sel;
}

/** True if `route` is a valid concrete route: a channel-token set, 'off' (drop),
 *  or 'inbox' (inbox only). Excludes the inherit sentinels 'default'/'app'. */
export function isConcreteRoute(route: string): boolean {
  if (route === 'off' || route === 'inbox') return true;
  const parts = route.split('+');
  if (parts.length === 0 || new Set(parts).size !== parts.length) return false;
  return parts.every((p) => {
    const idx = p.indexOf(':');
    const channel = idx === -1 ? p : p.slice(0, idx);
    if (!(CHANNELS as readonly string[]).includes(channel)) return false;
    return idx === -1 || INSTANCE_ID_RE.test(p.slice(idx + 1));
  });
}

/** Valid app-wide route value: a concrete route, or 'default' (inherit account default). */
export function isAppRoute(route: string): boolean {
  return route === 'default' || isConcreteRoute(route);
}

/** Valid per-category route value: a concrete route, or 'app' (inherit app-wide). */
export function isCategoryRoute(route: string): boolean {
  return route === 'app' || isConcreteRoute(route);
}

/** Management capability the user designated for an app. See MANAGEMENT-AUTH.md. */
export type Capability = 'none' | 'self' | 'full';

export interface RoutingCategory {
  category: string;
  /** Human display name (e.g. a webhook's name), if the app set one. */
  title?: string;
  description?: string;
  route: CategoryRoute;
}
export interface RoutingApp {
  sender: Did;
  title: string;
  /** App-wide route applied to everything from this app (and to categories set to 'app'). */
  route: AppRoute;
  /** What this app may manage on the user's behalf ('none'|'self'|'full'). */
  manage: Capability;
  /** Whether the user has muted this app (no alerts; still recorded in the inbox). */
  muted: boolean;
  /** Best-effort icon (app-supplied or Bluesky avatar) for the app screen header. */
  iconUrl?: string;
  categories: RoutingCategory[];
}
/** A selectable delivery instance for instance-level routing (one push device,
 *  one telegram chat, the verified email). `id` is the opaque token used in routes. */
export interface RouteInstance {
  id: string;
  label: string;
}
/** The user's current delivery instances per channel, for rendering route pickers. */
export type RouteInstances = Record<Channel, RouteInstance[]>;

/** An empty per-channel instance catalog (derived from CHANNELS, so adding a
 *  channel never leaves a literal stale). */
export function emptyRouteInstances(): RouteInstances {
  const out = {} as RouteInstances;
  for (const c of CHANNELS) out[c] = [];
  return out;
}

export interface RoutingConfig {
  defaultRoute: AlertRoute;
  apps: RoutingApp[];
  /** Available delivery instances per channel, so a route can target just one. */
  channels: RouteInstances;
}

/** A catalog entry for an app the user can enable from the web (binding-only). */
export interface AppInfo {
  did: Did;
  title: string;
  description?: string;
  iconUrl?: string;
}

export interface NotifsRpc {
  grant(did: Did, input: PubAtmoNotifyGrant.$input): Promise<PubAtmoNotifyGrant.$output>;
  revoke(did: Did, input: PubAtmoNotifyRevoke.$input): Promise<PubAtmoNotifyRevoke.$output>;
  denyPending(
    did: Did,
    input: PubAtmoNotifyDenyPending.$input,
  ): Promise<PubAtmoNotifyDenyPending.$output>;
  muteGrant(
    did: Did,
    input: PubAtmoNotifyMuteGrant.$input,
  ): Promise<PubAtmoNotifyMuteGrant.$output>;
  updateSettings(
    did: Did,
    input: PubAtmoNotifyUpdateSettings.$input,
  ): Promise<PubAtmoNotifyUpdateSettings.$output>;
  listGrants(did: Did): Promise<PubAtmoNotifyListGrants.$output>;
  listPending(did: Did): Promise<PubAtmoNotifyListPending.$output>;
  getSettings(did: Did): Promise<PubAtmoNotifyGetSettings.$output>;

  // Delivery targets — push devices, Telegram chats, emails (binding-only). One
  // user can have several of each; routes can target one specific instance.
  /** All of the user's delivery targets across channels. */
  listTargets(did: Did): Promise<TargetView[]>;
  /** Rename any target (give the device/chat/email a friendly name). */
  renameTarget(did: Did, id: string, label: string): Promise<{ ok: boolean }>;
  /** Remove any target by its id (unlink a Telegram chat, drop an email/device). */
  removeTarget(did: Did, id: string): Promise<{ ok: boolean }>;
  /** Send a test notification to all of the user's verified targets for one
   *  channel (a dashboard connectivity check). Returns how many it fired. */
  sendTest(did: Did, channel: Channel): Promise<{ delivered: number }>;

  // Telegram linking starts a deep-link handshake; call again to add another chat.
  // `label` is an optional user-chosen name applied to the chat once linked.
  linkChannel(
    did: Did,
    input: PubAtmoNotifyLinkChannel.$input,
    label?: string,
  ): Promise<PubAtmoNotifyLinkChannel.$output>;

  // Email: `linkEmail` adds an address and emails a code via comail; a user can
  // verify several. `label` is an optional user-chosen name (else the address is
  // used, hidden from apps). Remove one with `removeTarget`.
  linkEmail(did: Did, address: string, label?: string): Promise<{ ok: boolean }>;
  verifyEmail(did: Did, code: string): Promise<{ verified: boolean }>;

  // Webhook: add an https URL the relay POSTs notification JSON to. No
  // verification step (the user controls the endpoint); a user can add several.
  // Remove one with `removeTarget`. Throws on an invalid/non-public URL.
  addWebhook(did: Did, url: string, label: string): Promise<{ ok: boolean }>;

  // Bluesky DM: enable the relay's bot to DM this user (the recipient is always
  // the user's own DID, so there's no address and no verification — one per user,
  // idempotent). Disable with `removeTarget`.
  enableDM(did: Did): Promise<{ ok: boolean }>;

  // Web push (binding-only; no public lexicon). `unregisterWebPush` is the
  // "disable on this browser" path (keyed by the endpoint the SW reports).
  registerWebPush(did: Did, sub: PushSubscriptionInput): Promise<{ registered: boolean }>;
  unregisterWebPush(did: Did, endpoint: string): Promise<{ unregistered: boolean }>;

  // Inbox (binding-only; no public lexicon).
  listNotifications(did: Did, cursor?: string): Promise<ListNotificationsResult>;
  markRead(did: Did, input: MarkReadInput): Promise<{ marked: number }>;
  /** Permanently delete every notification from one app for this user. */
  clearNotificationsFromSender(did: Did, sender: Did): Promise<{ deleted: number }>;

  // Routing (binding-only). Three levels: category → app → account default.
  getRouting(did: Did): Promise<RoutingConfig>;
  setRouting(
    did: Did,
    sender: Did,
    category: string,
    route: CategoryRoute,
  ): Promise<{ ok: boolean }>;
  setAppRouting(did: Did, sender: Did, route: AppRoute): Promise<{ ok: boolean }>;
  setDefaultRoute(did: Did, route: AlertRoute): Promise<{ ok: boolean }>;

  /** Designate an app's management capability for this user ('none'|'self'|'full'). */
  setGrantManage(did: Did, sender: Did, manage: Capability): Promise<{ ok: boolean }>;

  /**
   * Cross-app login: verify a `pub.atmo.auth` service-auth JWT (issued by the
   * user's PDS, addressed to the relay DID, single-use) and return the issuer
   * DID. The ONLY method with no leading `did` — it is pre-auth; the DID is the
   * *result*, which the web app's /applogin route turns into a session. An
   * identity proof only: it grants no access to the user's PDS. See
   * CROSS-APP-AUTH.md.
   */
  verifyAppLogin(token: string): Promise<{ did: Did }>;

  /**
   * The hardcoded catalog of apps a user can enable notifications for from the
   * web. No leading `did` — the catalog is static. Enabling/disabling is just
   * `grant`/`revoke`; the relay fires a `subscriberChanged` callback to the app
   * (ENABLE-FROM-WEB.md).
   */
  listApps(): Promise<AppInfo[]>;
}
