// Hand-written (NOT generated by lex-cli, which only writes ./lexicons/).
//
// The relay's first-party management API. These 11 methods are deliberately NOT
// public XRPC: the relay exposes them ONLY over a Cloudflare service binding to
// the web app's server (see apps/relay/src/rpc/entrypoint.ts). This interface is
// the single contract both ends share — the relay's `RelayRpc` entrypoint
// `implements NotifsRpc`, and the web app types its `platform.env.RELAY` binding
// as `NotifsRpc`, so every call is type-checked end-to-end off the same source.
//
// Shapes reuse the lex-cli-generated `$input`/`$output` types, so the lexicon
// JSON stays the source of truth for request/response bodies even though these
// methods are no longer served as XRPC. The leading `did` argument is the
// authenticated user the caller (the trusted web server) vouches for.
import type { Did } from '@atcute/lexicons';

import type {
  PubAtmoNotifyDenyPending,
  PubAtmoNotifyGetSettings,
  PubAtmoNotifyGrant,
  PubAtmoNotifyLinkChannel,
  PubAtmoNotifyListChannels,
  PubAtmoNotifyListGrants,
  PubAtmoNotifyListPending,
  PubAtmoNotifyMuteGrant,
  PubAtmoNotifyRevoke,
  PubAtmoNotifyUnlinkChannel,
  PubAtmoNotifyUpdateSettings,
} from './lexicons/index.js';

/** A browser PushSubscription, flattened (binding-only; no public lexicon). */
export interface PushSubscriptionInput {
  endpoint: string;
  p256dh: string;
  auth: string;
  /** Auto-detected device label (from the User-Agent); preserved across re-subscribes. */
  label?: string;
}

/** A registered web push device (binding-only). */
export interface DeviceView {
  endpoint: string;
  label: string;
  createdAt: string;
}

/** A user's email delivery channel (binding-only). */
export interface EmailChannelView {
  address: string;
  /** false while a verification code is outstanding. */
  verified: boolean;
}

/** A notification as shown in the inbox (binding-only; no public lexicon). */
export interface NotificationView {
  id: string;
  sender: Did;
  category?: string;
  title: string;
  body: string;
  uri?: string;
  actors: string[];
  createdAt: string;
  read: boolean;
}

export interface ListNotificationsResult {
  notifications: NotificationView[];
  /** `created_at` cursor for the next (older) page; absent when there are no more. */
  cursor?: string;
  unread: number;
}

export interface MarkReadInput {
  ids?: string[];
  all?: boolean;
}

/** The alert channels a route can fire. Everything is in the inbox regardless. */
export const CHANNELS = ['push', 'telegram', 'email'] as const;
export type Channel = (typeof CHANNELS)[number];

// A route is a concrete channel SET, encoded as a `+`-joined string in canonical
// CHANNELS order ('off' = none) — e.g. 'push', 'push+email', 'off'. App-wide and
// per-category routes add the inherit sentinels 'default' / 'app'. Stored as a
// string; existing values ('push'/'telegram'/'push+telegram'/'off') are valid sets.
/** A concrete route: a `+`-joined channel set, or 'off'. */
export type AlertRoute = string;
/** App-wide route: a concrete route, or 'default' (inherit the account default). */
export type AppRoute = string;
/** Per-category route: a concrete route, or 'app' (inherit the app-wide route). */
export type CategoryRoute = string;

/** Parse a route string into its channels ('off'/'default'/'app'/'' → []). */
export function routeChannels(route: string): Channel[] {
  if (route === 'off' || route === 'default' || route === 'app' || route === '') return [];
  const set = new Set(route.split('+'));
  return CHANNELS.filter((c) => set.has(c));
}

/** Encode channels as a canonical route string ('off' when empty). */
export function channelsRoute(channels: readonly Channel[]): string {
  const ordered = CHANNELS.filter((c) => channels.includes(c));
  return ordered.length > 0 ? ordered.join('+') : 'off';
}

/** True if `route` is a valid concrete route (a channel set or 'off'). */
export function isConcreteRoute(route: string): boolean {
  if (route === 'off') return true;
  const parts = route.split('+');
  return (
    parts.length > 0 &&
    new Set(parts).size === parts.length &&
    parts.every((p) => (CHANNELS as readonly string[]).includes(p))
  );
}

/** Management capability the user designated for an app. See MANAGEMENT-AUTH.md. */
export type Capability = 'none' | 'self' | 'full';

export interface RoutingCategory {
  category: string;
  description?: string;
  route: CategoryRoute;
}
export interface RoutingApp {
  sender: Did;
  title: string;
  /** App-wide route applied to everything from this app (and to categories set to 'app'). */
  route: AppRoute;
  /** What this app may manage on the user's behalf ('none'|'self'|'full'). */
  manage: Capability;
  categories: RoutingCategory[];
}
export interface RoutingConfig {
  defaultRoute: AlertRoute;
  apps: RoutingApp[];
}

/** A catalog entry for an app the user can enable from the web (binding-only). */
export interface AppInfo {
  did: Did;
  title: string;
  description?: string;
  iconUrl?: string;
}

export interface NotifsRpc {
  grant(did: Did, input: PubAtmoNotifyGrant.$input): Promise<PubAtmoNotifyGrant.$output>;
  revoke(did: Did, input: PubAtmoNotifyRevoke.$input): Promise<PubAtmoNotifyRevoke.$output>;
  denyPending(
    did: Did,
    input: PubAtmoNotifyDenyPending.$input,
  ): Promise<PubAtmoNotifyDenyPending.$output>;
  muteGrant(
    did: Did,
    input: PubAtmoNotifyMuteGrant.$input,
  ): Promise<PubAtmoNotifyMuteGrant.$output>;
  linkChannel(
    did: Did,
    input: PubAtmoNotifyLinkChannel.$input,
  ): Promise<PubAtmoNotifyLinkChannel.$output>;
  unlinkChannel(
    did: Did,
    input: PubAtmoNotifyUnlinkChannel.$input,
  ): Promise<PubAtmoNotifyUnlinkChannel.$output>;
  updateSettings(
    did: Did,
    input: PubAtmoNotifyUpdateSettings.$input,
  ): Promise<PubAtmoNotifyUpdateSettings.$output>;
  listGrants(did: Did): Promise<PubAtmoNotifyListGrants.$output>;
  listPending(did: Did): Promise<PubAtmoNotifyListPending.$output>;
  listChannels(did: Did): Promise<PubAtmoNotifyListChannels.$output>;
  getSettings(did: Did): Promise<PubAtmoNotifyGetSettings.$output>;

  // Email channel (binding-only). `linkEmail` emails a verification code via comail.
  linkEmail(did: Did, address: string): Promise<{ ok: boolean }>;
  verifyEmail(did: Did, code: string): Promise<{ verified: boolean }>;
  unlinkEmail(did: Did): Promise<{ ok: boolean }>;
  getEmailChannel(did: Did): Promise<EmailChannelView | null>;

  // Web push (binding-only; no public lexicon).
  registerWebPush(did: Did, sub: PushSubscriptionInput): Promise<{ registered: boolean }>;
  unregisterWebPush(did: Did, endpoint: string): Promise<{ unregistered: boolean }>;
  listDevices(did: Did): Promise<DeviceView[]>;
  renameDevice(did: Did, endpoint: string, label: string): Promise<{ ok: boolean }>;

  // Inbox (binding-only; no public lexicon).
  listNotifications(did: Did, cursor?: string): Promise<ListNotificationsResult>;
  markRead(did: Did, input: MarkReadInput): Promise<{ marked: number }>;

  // Routing (binding-only). Three levels: category → app → account default.
  getRouting(did: Did): Promise<RoutingConfig>;
  setRouting(
    did: Did,
    sender: Did,
    category: string,
    route: CategoryRoute,
  ): Promise<{ ok: boolean }>;
  setAppRouting(did: Did, sender: Did, route: AppRoute): Promise<{ ok: boolean }>;
  setDefaultRoute(did: Did, route: AlertRoute): Promise<{ ok: boolean }>;

  /** Designate an app's management capability for this user ('none'|'self'|'full'). */
  setGrantManage(did: Did, sender: Did, manage: Capability): Promise<{ ok: boolean }>;

  /**
   * Cross-app login: verify a `pub.atmo.auth` service-auth JWT (issued by the
   * user's PDS, addressed to the relay DID, single-use) and return the issuer
   * DID. The ONLY method with no leading `did` — it is pre-auth; the DID is the
   * *result*, which the web app's /applogin route turns into a session. An
   * identity proof only: it grants no access to the user's PDS. See
   * CROSS-APP-AUTH.md.
   */
  verifyAppLogin(token: string): Promise<{ did: Did }>;

  /**
   * The hardcoded catalog of apps a user can enable notifications for from the
   * web. No leading `did` — the catalog is static. Enabling/disabling is just
   * `grant`/`revoke`; the relay fires a `subscriberChanged` callback to the app
   * (ENABLE-FROM-WEB.md).
   */
  listApps(): Promise<AppInfo[]>;
}
