// Hand-written (NOT generated by lex-cli, which only writes ./lexicons/).
//
// The relay's first-party management API. These 11 methods are deliberately NOT
// public XRPC: the relay exposes them ONLY over a Cloudflare service binding to
// the web app's server (see apps/relay/src/rpc/entrypoint.ts). This interface is
// the single contract both ends share — the relay's `RelayRpc` entrypoint
// `implements NotifsRpc`, and the web app types its `platform.env.RELAY` binding
// as `NotifsRpc`, so every call is type-checked end-to-end off the same source.
//
// Shapes reuse the lex-cli-generated `$input`/`$output` types, so the lexicon
// JSON stays the source of truth for request/response bodies even though these
// methods are no longer served as XRPC. The leading `did` argument is the
// authenticated user the caller (the trusted web server) vouches for.
import type { Did } from '@atcute/lexicons';

import type {
  ToolsAtmoNotifsDenyPending,
  ToolsAtmoNotifsGetSettings,
  ToolsAtmoNotifsGrant,
  ToolsAtmoNotifsLinkChannel,
  ToolsAtmoNotifsListChannels,
  ToolsAtmoNotifsListGrants,
  ToolsAtmoNotifsListPending,
  ToolsAtmoNotifsMuteGrant,
  ToolsAtmoNotifsRevoke,
  ToolsAtmoNotifsUnlinkChannel,
  ToolsAtmoNotifsUpdateSettings,
} from './lexicons/index.js';

/** A browser PushSubscription, flattened (binding-only; no public lexicon). */
export interface PushSubscriptionInput {
  endpoint: string;
  p256dh: string;
  auth: string;
  /** Auto-detected device label (from the User-Agent); preserved across re-subscribes. */
  label?: string;
}

/** A registered web push device (binding-only). */
export interface DeviceView {
  endpoint: string;
  label: string;
  createdAt: string;
}

/** A notification as shown in the inbox (binding-only; no public lexicon). */
export interface NotificationView {
  id: string;
  sender: Did;
  category?: string;
  title: string;
  body: string;
  uri?: string;
  actors: string[];
  createdAt: string;
  read: boolean;
}

export interface ListNotificationsResult {
  notifications: NotificationView[];
  /** `created_at` cursor for the next (older) page; absent when there are no more. */
  cursor?: string;
  unread: number;
}

export interface MarkReadInput {
  ids?: string[];
  all?: boolean;
}

/** Concrete alert routes (binding-only). Everything is in the inbox regardless; these gate alerts. */
export type AlertRoute = 'push' | 'telegram' | 'push+telegram' | 'off';
/** App-wide route: a concrete route, or 'default' (inherit the account default). */
export type AppRoute = AlertRoute | 'default';
/** Per-category route: a concrete route, or 'app' (inherit the app-wide route). */
export type CategoryRoute = AlertRoute | 'app';

export interface RoutingCategory {
  category: string;
  description?: string;
  route: CategoryRoute;
}
export interface RoutingApp {
  sender: Did;
  title: string;
  /** App-wide route applied to everything from this app (and to categories set to 'app'). */
  route: AppRoute;
  categories: RoutingCategory[];
}
export interface RoutingConfig {
  defaultRoute: AlertRoute;
  apps: RoutingApp[];
}

export interface NotifsRpc {
  grant(did: Did, input: ToolsAtmoNotifsGrant.$input): Promise<ToolsAtmoNotifsGrant.$output>;
  revoke(did: Did, input: ToolsAtmoNotifsRevoke.$input): Promise<ToolsAtmoNotifsRevoke.$output>;
  denyPending(
    did: Did,
    input: ToolsAtmoNotifsDenyPending.$input,
  ): Promise<ToolsAtmoNotifsDenyPending.$output>;
  muteGrant(
    did: Did,
    input: ToolsAtmoNotifsMuteGrant.$input,
  ): Promise<ToolsAtmoNotifsMuteGrant.$output>;
  linkChannel(
    did: Did,
    input: ToolsAtmoNotifsLinkChannel.$input,
  ): Promise<ToolsAtmoNotifsLinkChannel.$output>;
  unlinkChannel(
    did: Did,
    input: ToolsAtmoNotifsUnlinkChannel.$input,
  ): Promise<ToolsAtmoNotifsUnlinkChannel.$output>;
  updateSettings(
    did: Did,
    input: ToolsAtmoNotifsUpdateSettings.$input,
  ): Promise<ToolsAtmoNotifsUpdateSettings.$output>;
  listGrants(did: Did): Promise<ToolsAtmoNotifsListGrants.$output>;
  listPending(did: Did): Promise<ToolsAtmoNotifsListPending.$output>;
  listChannels(did: Did): Promise<ToolsAtmoNotifsListChannels.$output>;
  getSettings(did: Did): Promise<ToolsAtmoNotifsGetSettings.$output>;

  // Web push (binding-only; no public lexicon).
  registerWebPush(did: Did, sub: PushSubscriptionInput): Promise<{ registered: boolean }>;
  unregisterWebPush(did: Did, endpoint: string): Promise<{ unregistered: boolean }>;
  listDevices(did: Did): Promise<DeviceView[]>;
  renameDevice(did: Did, endpoint: string, label: string): Promise<{ ok: boolean }>;

  // Inbox (binding-only; no public lexicon).
  listNotifications(did: Did, cursor?: string): Promise<ListNotificationsResult>;
  markRead(did: Did, input: MarkReadInput): Promise<{ marked: number }>;

  // Routing (binding-only). Three levels: category → app → account default.
  getRouting(did: Did): Promise<RoutingConfig>;
  setRouting(
    did: Did,
    sender: Did,
    category: string,
    route: CategoryRoute,
  ): Promise<{ ok: boolean }>;
  setAppRouting(did: Did, sender: Did, route: AppRoute): Promise<{ ok: boolean }>;
  setDefaultRoute(did: Did, route: AlertRoute): Promise<{ ok: boolean }>;
}
